"""
    It helps us finding small variation in company names, such as -
        ('citi','citi bank')
        ('jpmorgan','jp morgan')
    etc.

"""
import re
from rapidfuzz.distance import Levenshtein
from rapidfuzz.utils import default_process
from collections import Counter
import itertools


## ==== SEARCH =========

def search_pattern(alias:str) -> str :
    """
    Construct a fuzzy regex pattern for a normalized company alias.

    The pattern generated by `denormalize_entity(...)` is wrapped with fuzzy matching constraints supported by the `regex` module.
    Maximum total edit distance increases with alias length, but is capped at 2.
    """
    n = min(2,len(alias)//6)
    pat = denormalize_entity(alias)
    return f"(?:{pat}){{i<=2,s<=1,d<=1,e<={n}}}"

## ==== =========


## ==== NORMALIZATION & DENORMALIZATION =========

REGEX_SPACE,REGEX_CAMEL = (
    re.compile(r'\s+'), # whitespace normalization
    re.compile(r'(?<=[a-z])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])') # split camel-case
)
def normalize_entity(ent:str) -> str :
    """
    Normalize a company/entity name into a canonical form suitable for
    alias comparison.

    Workflow
    --------
        1. Split CamelCase words (e.g. 'JPMorgan' -> 'JP Morgan').
        2. Convert to lowercase and remove punctuation using `rapidfuzz.utils.default_process(...)`.
        3. Collapse consecutive whitespaces into a single space.

    The resulting string preserves word boundaries so that `denormalize_entity(...)` can later reconstruct a flexible regex.

    Examples
    --------
    >>> normalize_entity("J.P. Morgan Chase")
    'j p morgan chase'

    >>> normalize_entity("JPMorgan Chase")
    'jp morgan chase'

    >>> normalize_entity("Cash-App")
    'cash app'

    >>> normalize_entity("Capital   One, Financial")
    'capital one financial'

    """
    # recover CamelCase before lower-casing ----
    ent = REGEX_CAMEL.sub(' ', ent)
    # ----
    # lowercase + remove punctuation ----
    ent = default_process(ent)
    # ----
    # collapse repeated spaces ----
    ent = REGEX_SPACE.sub(' ',ent)
    # ----
    return ent.strip()


REGEX_ALNUM,SEP_PATTERN = (
    re.compile(r'[A-Za-z0-9]+'), # identify consecutive alphanumeric chars
    r'[\s.,-]*' # common word-separators
)
def denormalize_entity(ent:str) ->str :
    """
    Convert a normalized entity into a regex pattern capable of matching
    common surface variations in free text.

    Matching rules
    --------------
        * The first word is always required.
        * The second word (if present) is also required.
        * Remaining words become optional suffixes.
        * Word separators (' ', '.', ',', '-') are treated as equivalent.
        * Zero separators are allowed, so concatenated words also match (e.g. 'CashApp', 'JPMorgan').

    Examples
    --------
    >>> denormalize_entity("equifax")
    '\\bequifax\\b'

    >>> denormalize_entity("american express")
    '\\bamerican[\\s.,-]*express\\b'

    >>> denormalize_entity("jp morgan chase")
    '\\bjp[\\s.,-]*morgan(?:[\\s.,-]*chase)?\\b'

    """
    words = REGEX_ALNUM.findall(ent)
    # base ----
    pattern = re.escape(words[0])
    if len(words) == 1 : # handle sinle word cases
        return r'\b' + pattern + r'\b'
    n_required = 2 if min(len(words[0]),len(words[1]))>2 else 3
    for word in words[1:n_required] : 
        pattern += (SEP_PATTERN + re.escape(word))
    # If either of the first two words is very short (≤2 characters),
    # require the first three words before making the remaining suffix optional.
    # This reduces false positives caused by fuzzy matching.
    # ----
    # optional ----
    for word in words[n_required:] :
        pattern += f"(?:{SEP_PATTERN}{re.escape(word)})?"
    # ----
    return r'\b' + pattern + r'\b'

## ==== =========


## ==== COUNTER =========

def _is_alias(s1:str,s2:str,*,score_cutoff:float=0.96) -> bool :
    """ `rapidfuzz.distance.Levenshtein.normalized_similarity(...)` wrapper """
    # regex matching uses 'Levenshtein Distance'
    return bool(
        Levenshtein.normalized_similarity(
            s1,s2,
            score_cutoff=score_cutoff
        )
    )
    
def merged_counter(list_of_list:list[list],n:int|None=10,*,fuzzy:bool=True,score_cutoff:float=0.96) -> list[tuple] :
    """
    Flatten a nested list of strings and return the most frequent elements via `collections.Counter(...).most_common(n)`.

    When `fuzzy=True`, similar strings are greedily consolidated before computing the final frequencies 
    using `rapidfuzz.distance.Levenshtein.normalized_similarity(...)`.

    """
    merged = itertools.chain.from_iterable(list_of_list)
    counted = Counter(merged)
    if not fuzzy : return counted.most_common(n)
    # even though we have counted all unique strings, we can consolidate further by fuzzy-match
    k = 1
    sorted_desc = counted.most_common(k+1)
    while len(sorted_desc)>k :
        unique = sorted_desc[:k]
        current_entity,count = sorted_desc[k]
        alias = None
        for visited_entity,_ in unique :
            if _is_alias(current_entity,visited_entity,score_cutoff=score_cutoff) :
                alias = True
                # merge the current count with existing alias count
                counted[visited_entity] += count
                del counted[current_entity]
                break
        if alias is None : k += 1
        # always reorder the elements before moving to next iteration
        # this is a greedy algorithm, 
        #   that finds the largest existing group with similar name of the current entity to merge
        #   if no existing match found, current entity remains its own group
        # Example 
        #   original : counted={str1:10, str2:5, str3:2}
        #   step-1 : _is_alias(str1,str2)=True, {str1:(10+5), str3:2}-->counted
        #   step-2 : _is_alias(str1,str3)=False, {str1:15, str3:2}-->counted ; _is_alias(str2,str3) is not considered any more
        sorted_desc = counted.most_common(k+1)
    # when len(most_common(k+1))>k fails, it implies no more elements to explore
    return sorted_desc[:n]

## ==== =========